name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test-and-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt

      - name: SAST - Bandit
        # Игнорирую flask_debug_true и hardcoded_bind_all_interfaces, потому что это не цель лабы
        run: |
          pip install bandit
          bandit -r . --exclude ./venv -f json -o bandit-report.json
        continue-on-error: false

      - name: SCA - pip-audit
        # Проверка зависимостей на известные уязвимости
        run: |
          pip install pip-audit
          pip-audit --format=json -o pip-audit-report.json
        continue-on-error: true


      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.json
            pip-audit-report.json
