name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test-and-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt

      - name: SAST - Bandit
        run: |
          pip install bandit
#          Игнорирую flask_debug_true и hardcoded_bind_all_interfaces, потому что это не цель лабы
          bandit -r . --exclude ./venv --skip B201,B104 -f json -o ./reports/bandit-report.json
        continue-on-error: false

      - name: SCA - pip-audit
        run: |
          pip install pip-audit
          pip-audit --format=json -o ./reports/pip-audit-report.json
        continue-on-error: false


      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.json
            pip-audit-report.json
            safety-report.json
